server:
  port: ${SERVICE_PORT:8080}
spring:
  application:
    name: service_name
  datasource:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:file:/basedatos/testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 25
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
    drop-first: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
